import { BlogCard } from "../components/BlogCard"

export const Blogs = () => {
  return (
    <div className="flex justify-center">
        <div  className="max-w-xl">
            <BlogCard 
                authorName={"John Doe"}
                title={"TITLE OF THE BLOG"}
                content={"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, culpa impedit esse qui modi sed beatae temporibus aliquam? Harum cumque necessitatibus nisi omnis blanditiis. Cupiditate qui distinctio eos quisquam provident doloribus, omnis enim cumque atque perferendis? Esse, cumque! Eaque provident cum minima eius ipsa maiores maxime neque vel. Consequatur voluptatem ut atque nostrum, at ipsa impedit numquam aliquid illum porro asperiores ipsam possimus autem quidem quasi perferendis eos, nobis nemo doloribus accusantium voluptates. Voluptatum blanditiis quo iusto ipsum quas ducimus velit nesciunt molestiae accusantium, deleniti error eveniet, odit eius sequi, numquam repellendus magnam. Pariatur enim quaerat porro a temporibus quasi, autem, explicabo nostrum quam unde quis totam, labore similique et eaque accusantium dignissimos hic reiciendis placeat consequuntur? Et eaque nostrum iusto suscipit repudiandae quis omnis similique doloremque quas recusandae non, optio incidunt vel asperiores repellat dicta nemo enim aliquam quae excepturi voluptatum qui ratione, sapiente explicabo. Consequuntur sed voluptate exercitationem a, deleniti amet voluptas qui, facilis corrupti iste eaque nesciunt tenetur, temporibus reiciendis voluptates cumque! Atque velit cupiditate enim quam fugit, ut laudantium neque rerum doloremque iusto reiciendis saepe architecto sunt deleniti dolores, incidunt recusandae. Veritatis exercitationem, obcaecati ea id necessitatibus, iusto nesciunt blanditiis vero est quo earum, ut hic sequi voluptatum repellendus nisi dolores. Maiores ea quidem voluptates magnam, est repudiandae delectus a eveniet. Totam at repellat cumque quos id explicabo incidunt iusto earum corrupti a amet reprehenderit quaerat, nesciunt doloremque laboriosam magni. Eaque voluptate odit dolorem temporibus magni veritatis recusandae quisquam, ad perferendis magnam. Ducimus animi quidem atque, modi dolorum dolores neque sequi cupiditate, rerum molestiae voluptatibus facilis veritatis incidunt error est dolor sunt deserunt, fuga labore ipsa consequuntur expedita nobis nostrum. Illum corrupti vitae aut quis, aspernatur fugiat ducimus, tempore rem velit qui placeat dignissimos ut voluptate distinctio voluptatibus ipsum. Adipisci dignissimos corrupti magnam voluptatibus rem odit laudantium, vero ipsam a minima nesciunt, illum aut. Consequatur sed culpa dolorem unde natus nesciunt veritatis officiis ratione similique? Magnam reiciendis est hic inventore assumenda, corrupti, incidunt repudiandae provident, reprehenderit ullam deserunt id. Dicta, ratione illum, et placeat odio commodi doloremque, veniam nisi officia incidunt fugiat. Maiores fuga quidem nobis?"}
                publishedDate={"12-05-65"}
                />
            <BlogCard 
                authorName={"John Doe"}
                title={"TITLE OF THE BLOG"}
                content={"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, culpa impedit esse qui modi sed beatae temporibus aliquam? Harum cumque necessitatibus nisi omnis blanditiis. Cupiditate qui distinctio eos quisquam provident doloribus, omnis enim cumque atque perferendis? Esse, cumque! Eaque provident cum minima eius ipsa maiores maxime neque vel. Consequatur voluptatem ut atque nostrum, at ipsa impedit numquam aliquid illum porro asperiores ipsam possimus autem quidem quasi perferendis eos, nobis nemo doloribus accusantium voluptates. Voluptatum blanditiis quo iusto ipsum quas ducimus velit nesciunt molestiae accusantium, deleniti error eveniet, odit eius sequi, numquam repellendus magnam. Pariatur enim quaerat porro a temporibus quasi, autem, explicabo nostrum quam unde quis totam, labore similique et eaque accusantium dignissimos hic reiciendis placeat consequuntur? Et eaque nostrum iusto suscipit repudiandae quis omnis similique doloremque quas recusandae non, optio incidunt vel asperiores repellat dicta nemo enim aliquam quae excepturi voluptatum qui ratione, sapiente explicabo. Consequuntur sed voluptate exercitationem a, deleniti amet voluptas qui, facilis corrupti iste eaque nesciunt tenetur, temporibus reiciendis voluptates cumque! Atque velit cupiditate enim quam fugit, ut laudantium neque rerum doloremque iusto reiciendis saepe architecto sunt deleniti dolores, incidunt recusandae. Veritatis exercitationem, obcaecati ea id necessitatibus, iusto nesciunt blanditiis vero est quo earum, ut hic sequi voluptatum repellendus nisi dolores. Maiores ea quidem voluptates magnam, est repudiandae delectus a eveniet. Totam at repellat cumque quos id explicabo incidunt iusto earum corrupti a amet reprehenderit quaerat, nesciunt doloremque laboriosam magni. Eaque voluptate odit dolorem temporibus magni veritatis recusandae quisquam, ad perferendis magnam. Ducimus animi quidem atque, modi dolorum dolores neque sequi cupiditate, rerum molestiae voluptatibus facilis veritatis incidunt error est dolor sunt deserunt, fuga labore ipsa consequuntur expedita nobis nostrum. Illum corrupti vitae aut quis, aspernatur fugiat ducimus, tempore rem velit qui placeat dignissimos ut voluptate distinctio voluptatibus ipsum. Adipisci dignissimos corrupti magnam voluptatibus rem odit laudantium, vero ipsam a minima nesciunt, illum aut. Consequatur sed culpa dolorem unde natus nesciunt veritatis officiis ratione similique? Magnam reiciendis est hic inventore assumenda, corrupti, incidunt repudiandae provident, reprehenderit ullam deserunt id. Dicta, ratione illum, et placeat odio commodi doloremque, veniam nisi officia incidunt fugiat. Maiores fuga quidem nobis?"}
                publishedDate={"12-05-65"}
                />
            <BlogCard 
                authorName={"John Doe"}
                title={"TITLE OF THE BLOG"}
                content={"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, culpa impedit esse qui modi sed beatae temporibus aliquam? Harum cumque necessitatibus nisi omnis blanditiis. Cupiditate qui distinctio eos quisquam provident doloribus, omnis enim cumque atque perferendis? Esse, cumque! Eaque provident cum minima eius ipsa maiores maxime neque vel. Consequatur voluptatem ut atque nostrum, at ipsa impedit numquam aliquid illum porro asperiores ipsam possimus autem quidem quasi perferendis eos, nobis nemo doloribus accusantium voluptates. Voluptatum blanditiis quo iusto ipsum quas ducimus velit nesciunt molestiae accusantium, deleniti error eveniet, odit eius sequi, numquam repellendus magnam. Pariatur enim quaerat porro a temporibus quasi, autem, explicabo nostrum quam unde quis totam, labore similique et eaque accusantium dignissimos hic reiciendis placeat consequuntur? Et eaque nostrum iusto suscipit repudiandae quis omnis similique doloremque quas recusandae non, optio incidunt vel asperiores repellat dicta nemo enim aliquam quae excepturi voluptatum qui ratione, sapiente explicabo. Consequuntur sed voluptate exercitationem a, deleniti amet voluptas qui, facilis corrupti iste eaque nesciunt tenetur, temporibus reiciendis voluptates cumque! Atque velit cupiditate enim quam fugit, ut laudantium neque rerum doloremque iusto reiciendis saepe architecto sunt deleniti dolores, incidunt recusandae. Veritatis exercitationem, obcaecati ea id necessitatibus, iusto nesciunt blanditiis vero est quo earum, ut hic sequi voluptatum repellendus nisi dolores. Maiores ea quidem voluptates magnam, est repudiandae delectus a eveniet. Totam at repellat cumque quos id explicabo incidunt iusto earum corrupti a amet reprehenderit quaerat, nesciunt doloremque laboriosam magni. Eaque voluptate odit dolorem temporibus magni veritatis recusandae quisquam, ad perferendis magnam. Ducimus animi quidem atque, modi dolorum dolores neque sequi cupiditate, rerum molestiae voluptatibus facilis veritatis incidunt error est dolor sunt deserunt, fuga labore ipsa consequuntur expedita nobis nostrum. Illum corrupti vitae aut quis, aspernatur fugiat ducimus, tempore rem velit qui placeat dignissimos ut voluptate distinctio voluptatibus ipsum. Adipisci dignissimos corrupti magnam voluptatibus rem odit laudantium, vero ipsam a minima nesciunt, illum aut. Consequatur sed culpa dolorem unde natus nesciunt veritatis officiis ratione similique? Magnam reiciendis est hic inventore assumenda, corrupti, incidunt repudiandae provident, reprehenderit ullam deserunt id. Dicta, ratione illum, et placeat odio commodi doloremque, veniam nisi officia incidunt fugiat. Maiores fuga quidem nobis?"}
                publishedDate={"12-05-65"}
                />
            <BlogCard 
                authorName={"John Doe"}
                title={"TITLE OF THE BLOG"}
                content={"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, culpa impedit esse qui modi sed beatae temporibus aliquam? Harum cumque necessitatibus nisi omnis blanditiis. Cupiditate qui distinctio eos quisquam provident doloribus, omnis enim cumque atque perferendis? Esse, cumque! Eaque provident cum minima eius ipsa maiores maxime neque vel. Consequatur voluptatem ut atque nostrum, at ipsa impedit numquam aliquid illum porro asperiores ipsam possimus autem quidem quasi perferendis eos, nobis nemo doloribus accusantium voluptates. Voluptatum blanditiis quo iusto ipsum quas ducimus velit nesciunt molestiae accusantium, deleniti error eveniet, odit eius sequi, numquam repellendus magnam. Pariatur enim quaerat porro a temporibus quasi, autem, explicabo nostrum quam unde quis totam, labore similique et eaque accusantium dignissimos hic reiciendis placeat consequuntur? Et eaque nostrum iusto suscipit repudiandae quis omnis similique doloremque quas recusandae non, optio incidunt vel asperiores repellat dicta nemo enim aliquam quae excepturi voluptatum qui ratione, sapiente explicabo. Consequuntur sed voluptate exercitationem a, deleniti amet voluptas qui, facilis corrupti iste eaque nesciunt tenetur, temporibus reiciendis voluptates cumque! Atque velit cupiditate enim quam fugit, ut laudantium neque rerum doloremque iusto reiciendis saepe architecto sunt deleniti dolores, incidunt recusandae. Veritatis exercitationem, obcaecati ea id necessitatibus, iusto nesciunt blanditiis vero est quo earum, ut hic sequi voluptatum repellendus nisi dolores. Maiores ea quidem voluptates magnam, est repudiandae delectus a eveniet. Totam at repellat cumque quos id explicabo incidunt iusto earum corrupti a amet reprehenderit quaerat, nesciunt doloremque laboriosam magni. Eaque voluptate odit dolorem temporibus magni veritatis recusandae quisquam, ad perferendis magnam. Ducimus animi quidem atque, modi dolorum dolores neque sequi cupiditate, rerum molestiae voluptatibus facilis veritatis incidunt error est dolor sunt deserunt, fuga labore ipsa consequuntur expedita nobis nostrum. Illum corrupti vitae aut quis, aspernatur fugiat ducimus, tempore rem velit qui placeat dignissimos ut voluptate distinctio voluptatibus ipsum. Adipisci dignissimos corrupti magnam voluptatibus rem odit laudantium, vero ipsam a minima nesciunt, illum aut. Consequatur sed culpa dolorem unde natus nesciunt veritatis officiis ratione similique? Magnam reiciendis est hic inventore assumenda, corrupti, incidunt repudiandae provident, reprehenderit ullam deserunt id. Dicta, ratione illum, et placeat odio commodi doloremque, veniam nisi officia incidunt fugiat. Maiores fuga quidem nobis?"}
                publishedDate={"12-05-65"}
                />
        </div>
    </div>
  )
}
